name: deploy
# If at least one path matches a pattern in the paths filter, the workflow runs.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        env:
          SECRET_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -oStrictHostKeyChecking=no -i id_rsa xs098000@xs098000.xsrv.jp -p 10022 "ls"
