name: lint
# If at least one path matches a pattern in the paths filter, the workflow runs.
on:
  push:
    branches:
      - main
    paths:
      - "ago-theme/**"
  pull_request:
    branches:
      - main
    paths:
      - "ago-theme/**"
# Specify the working directory for all run steps in a workflow
defaults:
  run:
    working-directory: ago-theme

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages by Yarn
        run: yarn install
      - name: Lint files by eslint
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with: # shimataro/ssh-key-actionに渡すパラメーター
          private-key: ${{ secrets.SSH_KEY }} # 必須
          name: id_rsa # 省略可
      - name: run deploy script
        run: bash deploy.sh
